import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Formulário</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>

      </main>

      <footer>
        <p>footer</p>
      </footer>
    </div>
  );
};

export default Home;
